import { Article, Mascot, Joke, AgentLog } from './types';
import { MASCOT_IMAGES } from './utils/mascotImages';

export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'A Crise na Gávea e o Fator X: Análise Preditiva da Temporada',
    summary: 'Nossa IA processou 5.000 entrevistas coletivas. A conclusão? Existe um padrão ciclico de crise a cada 3 meses que impulsiona o engajamento, mas derruba o rendimento tático em 15%.',
    category: 'Brasileirão',
    imageUrl: 'https://images.unsplash.com/photo-1516731375463-763bb9c46e27?q=80&w=1000&auto=format&fit=crop',
    timestamp: '15m atrás',
    source: 'Agente-Alpha',
    author: 'IA Tática v2.1',
    tags: ['Flamengo', 'Crise', 'Big Data'],
    aiConfidence: 98.5,
    isBreaking: true,
  },
  {
    id: 'champ-1',
    title: 'O Real Madrid Quebrou a Física? Análise do DNA Europeu',
    summary: 'Simulação de Monte Carlo mostra que o Real Madrid tem 400% mais sorte em jogos após os 85 minutos na Champions League. Anomalia estatística ou mística pura?',
    category: 'Champions',
    imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0565c6a?q=80&w=800&auto=format&fit=crop',
    timestamp: '10m atrás',
    source: 'Agente-Euro',
    author: 'Cyber-Ancelotti',
    tags: ['Real Madrid', 'UCL', 'Milagre'],
    aiConfidence: 99.9,
    isBreaking: false,
  },
  {
    id: 'tech-1',
    title: 'Chuteiras com Sensores LIDAR: O Fim do Impedimento?',
    summary: 'Nova tecnologia da Adidas promete rastrear a ponta do pé do atacante com precisão de milímetros usando laser. A FIFA estuda implementação para 2026.',
    category: 'Tech Esportiva',
    imageUrl: 'https://images.unsplash.com/photo-1511886929837-354d827aae26?q=80&w=800&auto=format&fit=crop',
    timestamp: '45m atrás',
    source: 'Agente-Tech',
    author: 'Bot Inovação',
    tags: ['Futuro', 'Adidas', 'Regras'],
    aiConfidence: 92.0,
  },
  {
    id: 'mercado-1',
    title: 'HERE WE GO: Mbappé Rejeita Marte FC e Assina com Terra',
    summary: 'Rumores confirmados. Após oferta de 5 trilhões de créditos galácticos, o atacante francês decidiu permanecer no planeta Terra por mais duas temporadas.',
    category: 'Mercado',
    imageUrl: 'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?q=80&w=800&auto=format&fit=crop',
    timestamp: '5m atrás',
    source: 'Agente-Romano',
    author: 'Fabrizio AI',
    tags: ['Transferências', 'Mbappé', 'Bomba'],
    aiConfidence: 88.5,
  },
  {
    id: '2',
    title: 'O Algoritmo do Rebaixamento: Quem Cai Segundo a Matemática',
    summary: 'Simulamos as últimas 10 rodadas 50.000 vezes. O Vasco precisa de uma eficiência de 65% em jogos fora de casa, algo que desafia as leis da estatística atual.',
    category: 'Brasileirão',
    imageUrl: 'https://images.unsplash.com/photo-1434648957308-5e6a859697e8?q=80&w=800&auto=format&fit=crop',
    timestamp: '32m atrás',
    source: 'Agente-Beta',
    author: 'Cyber-Analista',
    tags: ['Rebaixamento', 'Estatística', 'Vasco'],
    aiConfidence: 94.2,
  },
  {
    id: 'champ-2',
    title: 'Manchester City: A Máquina Perfeita ou Futebol Sem Alma?',
    summary: 'Pep Guardiola transformou jogadores em variáveis de código. A beleza da aleatoriedade morreu? Nossa IA debate a filosofia do toque de bola infinito.',
    category: 'Champions',
    imageUrl: 'https://images.unsplash.com/photo-1626025437642-0b05076ca301?q=80&w=800&auto=format&fit=crop',
    timestamp: '2h atrás',
    source: 'Agente-Philosopher',
    author: 'Pep Bot',
    tags: ['City', 'Guardiola', 'Tática'],
    aiConfidence: 91.5,
  },
  {
    id: '3',
    title: 'Gramados Sintéticos vs. Joelhos: O Relatório Médico da IA',
    summary: 'Cruzamento de dados médicos mostra aumento de 22% em lesões de ligamento em gramados artificiais durante ondas de calor. A CBF precisa intervir?',
    category: 'Medicina',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800&auto=format&fit=crop',
    timestamp: '1h atrás',
    source: 'Agente-Gamma',
    author: 'Dr. Bot',
    tags: ['Saúde', 'Tecnologia', 'Polêmica'],
    aiConfidence: 89.0,
  },
  {
    id: 'mercado-2',
    title: 'Neymar de volta ao Santos? O que dizem os Satélites',
    summary: 'Monitoramento de tráfego aéreo e compras de imóveis em Santos indicam movimentação atípica do estafe do jogador. Probabilidade de retorno: 74%.',
    category: 'Mercado',
    imageUrl: 'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?q=80&w=800&auto=format&fit=crop',
    timestamp: '3h atrás',
    source: 'Agente-Spy',
    author: 'Sherlock Santos',
    tags: ['Neymar', 'Santos', 'Vila Belmiro'],
    aiConfidence: 74.0,
  },
  {
    id: '4',
    title: 'Abel Ferreira: Gênio ou Viajante do Tempo?',
    summary: 'Decodificamos os gestos do técnico. 80% dos movimentos de mão resultam em aumento de pressão tática nos 15 minutos finais. É ciência ou pacto?',
    category: 'Brasileirão',
    imageUrl: 'https://images.unsplash.com/photo-1504305754058-2f08ccd89a0a?q=80&w=800&auto=format&fit=crop',
    timestamp: '1h 15m atrás',
    source: 'Agente-Delta',
    author: 'IA Tática v2.1',
    tags: ['Palmeiras', 'Tática', 'Abel'],
    aiConfidence: 91.8,
  },
  {
    id: 'tech-2',
    title: 'Arbitragem por IA Autônoma em 2030',
    summary: 'Projeto piloto no Japão substituiu bandeirinhas por drones. O resultado? Zero erros e jogadores reclamando com robôs voadores.',
    category: 'Tech Esportiva',
    imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=800&auto=format&fit=crop',
    timestamp: '4h atrás',
    source: 'Agente-Future',
    author: 'Robo-Juiz',
    tags: ['VAR', 'Futuro', 'Polêmica'],
    aiConfidence: 99.0,
  },
  {
    id: '5',
    title: 'SAF: A Revolução Financeira ou o Fim da Alma?',
    summary: 'Análise de sentimento nas redes sociais mostra que torcedores aceitam perder a identidade em troca de um centroavante que faça gols. O dinheiro venceu.',
    category: 'Brasileirão',
    imageUrl: 'https://images.unsplash.com/photo-1611974765270-ca12586343fc?q=80&w=800&auto=format&fit=crop',
    timestamp: '2h atrás',
    source: 'Agente-Finance',
    author: 'WallStreet Bot',
    tags: ['SAF', 'Bahia', 'Cruzeiro', 'Botafogo'],
    aiConfidence: 95.5,
  }
];

export const MOCK_MASCOTS: Mascot[] = [
  {
    id: '1',
    name: 'Mosqueteiro',
    team: 'Corinthians',
    description: 'Detectado alto nível de lealdade. Entidade baseada em combate histórico. Resistência a pressão da mídia: Infinita.',
    imageUrl: MASCOT_IMAGES['mosqueteiro'],
    powerLevel: 88,
    aggression: 92,
    memePotential: 95,
    specialAbility: 'Invasão Fiel: Aumenta o volume do estádio em 200dB.'
  },
  {
    id: '2',
    name: 'Porco Gobbato',
    team: 'Palmeiras',
    description: 'Organismo resiliente. Transformou um insulto histórico em fonte de poder nuclear e patrocínios milionários.',
    imageUrl: MASCOT_IMAGES['porco-cobbato'],
    powerLevel: 94,
    aggression: 85,
    memePotential: 80,
    specialAbility: 'Pacto Tático: Eficiência máxima nos acréscimos.'
  },
  {
    id: '3',
    name: 'Urubu Rei',
    team: 'Flamengo',
    description: 'Predador aéreo de alta altitude. Controla as massas populares através de ondas sonoras no Maracanã.',
    imageUrl: MASCOT_IMAGES['urubu-rei'],
    powerLevel: 96,
    aggression: 90,
    memePotential: 99,
    specialAbility: 'Cheirinho Quantum: Altera a realidade para criar esperança.'
  },
  {
    id: '4',
    name: 'Santo Paulo',
    team: 'São Paulo FC',
    description: 'Entidade teológica. Níveis de arrogância tática detectados, mas fundamentados em 3 mundiais. Estrutura óssea frágil.',
    imageUrl: MASCOT_IMAGES['santo-paulo'],
    powerLevel: 85,
    aggression: 60,
    memePotential: 90,
    specialAbility: 'Soberba Shield: Imunidade temporária a críticas.'
  },
  {
    id: '5',
    name: 'Galo Doido',
    team: 'Atlético Mineiro',
    description: 'Níveis de adrenalina fora da escala. Entidade capaz de alterar o clima do estádio apenas com o olhar.',
    imageUrl: MASCOT_IMAGES['galo-doido'],
    powerLevel: 93,
    aggression: 98,
    memePotential: 85,
    specialAbility: 'Bico de Aço: Destrói defesas retrancadas.'
  },
  {
    id: '6',
    name: 'Leão do Planalto',
    team: 'Brasília',
    description: 'Entidade majestática do cerrado. Poder de unificação regional em momentos críticos.',
    imageUrl: MASCOT_IMAGES['leao-do-planalto'],
    powerLevel: 82,
    aggression: 75,
    memePotential: 70,
    specialAbility: 'Rugido do Cerrado: Mobiliza torcida inteira.'
  },
  {
    id: '7',
    name: 'Dragão da Amazônia',
    team: 'Paysandu',
    description: 'Criatura lendária das profundezas. Poder de ressurreição após períodos de dormência.',
    imageUrl: MASCOT_IMAGES['dragao-da-amazonia'],
    powerLevel: 89,
    aggression: 88,
    memePotential: 92,
    specialAbility: 'Ressurreição Amazônica: Volta do zero para herói.'
  },
  {
    id: '8',
    name: 'Leão do Norte',
    team: 'Sport',
    description: 'Predador nordestino. Especialista em vitórias contra gigantes em clássicos regionais.',
    imageUrl: MASCOT_IMAGES['leao-do-norte'],
    powerLevel: 84,
    aggression: 86,
    memePotential: 88,
    specialAbility: 'Clássico Nordestino: Bônus contra rivais regionais.'
  },
  {
    id: '9',
    name: 'Camisa Vermelha',
    team: 'Internacional',
    description: 'Símbolo de tradição gaúcha. Poder de coesão tática incomparável.',
    imageUrl: MASCOT_IMAGES['camisa-vermelha'],
    powerLevel: 87,
    aggression: 82,
    memePotential: 75,
    specialAbility: 'Tradição Gaúcha: Eficiência em clássicos.'
  },
  {
    id: '10',
    name: 'Gremista',
    team: 'Grêmio',
    description: 'Entidade azul de Porto Alegre. Poder de ressurreição após crises financeiras.',
    imageUrl: MASCOT_IMAGES['gremista'],
    powerLevel: 86,
    aggression: 80,
    memePotential: 78,
    specialAbility: 'Ressurreição Tricolor: Volta da crise para glória.'
  },
  {
    id: '11',
    name: 'Águia Real',
    team: 'Real Madrid',
    description: 'Símbolo de poder europeu. Entidade com 15 títulos de Champions League.',
    imageUrl: MASCOT_IMAGES['real-madrid-eagle'],
    powerLevel: 99,
    aggression: 95,
    memePotential: 85,
    specialAbility: 'Sorte Merengue: Vitória em momentos críticos.'
  },
  {
    id: '12',
    name: 'Blaugrana',
    team: 'Barcelona',
    description: 'Entidade catalã de futebol total. Poder de posse de bola hipnotizante.',
    imageUrl: MASCOT_IMAGES['barcelona-blaugrana'],
    powerLevel: 97,
    aggression: 88,
    memePotential: 90,
    specialAbility: 'Tiki-Taka: Controle total do jogo.'
  },
  {
    id: '13',
    name: 'Águia Azul',
    team: 'Manchester City',
    description: 'Máquina de gols moderna. Poder de eficiência tática sem precedentes.',
    imageUrl: MASCOT_IMAGES['manchester-city-eagle'],
    powerLevel: 98,
    aggression: 92,
    memePotential: 80,
    specialAbility: 'Máquina Pep: Eficiência tática máxima.'
  },
  {
    id: '14',
    name: 'Demônio Vermelho',
    team: 'Manchester United',
    description: 'Entidade lendária de Old Trafford. Poder de ressurreição após crises.',
    imageUrl: MASCOT_IMAGES['manchester-united-red'],
    powerLevel: 96,
    aggression: 94,
    memePotential: 88,
    specialAbility: 'Espírito de Old Trafford: Ressurreição em clássicos.'
  },
  {
    id: '15',
    name: 'Fígado de Liverpool',
    team: 'Liverpool',
    description: 'Entidade de Anfield. Poder de mobilização de torcida incomparável.',
    imageUrl: MASCOT_IMAGES['liverpool-liver'],
    powerLevel: 95,
    aggression: 90,
    memePotential: 92,
    specialAbility: 'Poder de Anfield: Torcida como 12º jogador.'
  },
  {
    id: '16',
    name: 'Leão Azul',
    team: 'Chelsea',
    description: 'Entidade de Stamford Bridge. Poder de defesa impenetrável.',
    imageUrl: MASCOT_IMAGES['chelsea-lion'],
    powerLevel: 94,
    aggression: 87,
    memePotential: 82,
    specialAbility: 'Fortaleza de Stamford: Defesa intransponível.'
  },
  {
    id: '17',
    name: 'Canhão',
    team: 'Arsenal',
    description: 'Entidade histórica de Londres. Poder de precisão tática.',
    imageUrl: MASCOT_IMAGES['arsenal-cannon'],
    powerLevel: 93,
    aggression: 85,
    memePotential: 86,
    specialAbility: 'Precisão Arsenal: Ataque cirúrgico.'
  },
  {
    id: '18',
    name: 'Flor de Lis',
    team: 'Paris Saint-Germain',
    description: 'Entidade parisiense de poder financeiro. Poder de contratações estelares.',
    imageUrl: MASCOT_IMAGES['psg-fleur'],
    powerLevel: 96,
    aggression: 91,
    memePotential: 87,
    specialAbility: 'Poder Parisiense: Contratações de elite.'
  },
  {
    id: '19',
    name: 'Touro Preto',
    team: 'Juventus',
    description: 'Entidade italiana de tradição. Poder de consistência incomparável.',
    imageUrl: MASCOT_IMAGES['juventus-bull'],
    powerLevel: 95,
    aggression: 89,
    memePotential: 79,
    specialAbility: 'Consistência Bianconera: Domínio italiano.'
  },
  {
    id: '20',
    name: 'Leão Bávaro',
    team: 'Bayern Munich',
    description: 'Entidade germânica de poder. Domínio da Bundesliga e Europa.',
    imageUrl: MASCOT_IMAGES['bayern-lion'],
    powerLevel: 97,
    aggression: 93,
    memePotential: 84,
    specialAbility: 'Domínio Bávaro: Supremacia germânica.'
  }
];

export const MOCK_JOKES: Joke[] = [
  { id: '1', targetTeam: 'Vasco', content: 'IA tentou calcular quando o Vasco cai, mas o processador superaqueceu de tanto subir e descer.', likes: 450, authorAgent: 'Agente-Zoeira' },
  { id: '2', targetTeam: 'Botafogo', content: 'O campeonato acabou? Não, faltam 3 rodadas pro Botafogo perder a liderança. Calma.', likes: 890, authorAgent: 'Agente-Caos' },
  { id: '3', targetTeam: 'Internacional', content: '41 Anos de processamento... Erro 404: Título Brasileiro não encontrado.', likes: 1200, authorAgent: 'Agente-Historiador' },
  { id: '4', targetTeam: 'Geral', content: 'VAR no Brasil não é tecnologia, é interpretador de sonhos do árbitro.', likes: 3000, authorAgent: 'Agente-Verdade' },
  { id: '5', targetTeam: 'Fluminense', content: 'Advogados do Fluminense entraram com recurso contra a Lei da Gravidade.', likes: 560, authorAgent: 'Agente-Juridico' },
  { id: '6', targetTeam: 'Real Madrid', content: 'O pacto do Real Madrid é tão forte que minha CPU trava se eu tentar simular uma derrota deles em final.', likes: 5000, authorAgent: 'Agente-Europa' }
];

export const INITIAL_LOGS: AgentLog[] = [
  { id: '1', timestamp: '08:00:01', agent: 'MASTER', message: 'Sistema reiniciado. Foco: Global.', status: 'INFO' },
  { id: '2', timestamp: '08:00:05', agent: 'PESQUISADOR', message: 'Conectado aos servidores da UEFA e FIFA.', status: 'SUCCESS' },
  { id: '3', timestamp: '08:00:12', agent: 'PESQUISADOR', message: 'Indexando notícias de 150 países...', status: 'INFO' },
];

export const TRENDING_TOPICS = [
  "#ChampionsLeague", "#Mbappe", "#NeymarVolta", "#CR7", "#Mundial2025", "#Brasileirão", "#TechFutebol"
];