import { Article, Mascot, Joke, AgentLog } from './types';

export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'A Crise na Gávea e o Fator X: Análise Preditiva da Temporada',
    summary: 'Nossa IA processou 5.000 entrevistas coletivas. A conclusão? Existe um padrão ciclico de crise a cada 3 meses que impulsiona o engajamento, mas derruba o rendimento tático em 15%.',
    category: 'Brasileirão',
    imageUrl: 'https://images.unsplash.com/photo-1516731375463-763bb9c46e27?q=80&w=1000&auto=format&fit=crop',
    timestamp: '15m atrás',
    source: 'Agente-Alpha',
    author: 'IA Tática v2.1',
    tags: ['Flamengo', 'Crise', 'Big Data'],
    aiConfidence: 98.5,
    isBreaking: true,
  },
  {
    id: 'champ-1',
    title: 'O Real Madrid Quebrou a Física? Análise do DNA Europeu',
    summary: 'Simulação de Monte Carlo mostra que o Real Madrid tem 400% mais sorte em jogos após os 85 minutos na Champions League. Anomalia estatística ou mística pura?',
    category: 'Champions',
    imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0565c6a?q=80&w=800&auto=format&fit=crop',
    timestamp: '10m atrás',
    source: 'Agente-Euro',
    author: 'Cyber-Ancelotti',
    tags: ['Real Madrid', 'UCL', 'Milagre'],
    aiConfidence: 99.9,
    isBreaking: false,
  },
  {
    id: 'tech-1',
    title: 'Chuteiras com Sensores LIDAR: O Fim do Impedimento?',
    summary: 'Nova tecnologia da Adidas promete rastrear a ponta do pé do atacante com precisão de milímetros usando laser. A FIFA estuda implementação para 2026.',
    category: 'Tech Esportiva',
    imageUrl: 'https://images.unsplash.com/photo-1511886929837-354d827aae26?q=80&w=800&auto=format&fit=crop',
    timestamp: '45m atrás',
    source: 'Agente-Tech',
    author: 'Bot Inovação',
    tags: ['Futuro', 'Adidas', 'Regras'],
    aiConfidence: 92.0,
  },
  {
    id: 'mercado-1',
    title: 'HERE WE GO: Mbappé Rejeita Marte FC e Assina com Terra',
    summary: 'Rumores confirmados. Após oferta de 5 trilhões de créditos galácticos, o atacante francês decidiu permanecer no planeta Terra por mais duas temporadas.',
    category: 'Mercado',
    imageUrl: 'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?q=80&w=800&auto=format&fit=crop',
    timestamp: '5m atrás',
    source: 'Agente-Romano',
    author: 'Fabrizio AI',
    tags: ['Transferências', 'Mbappé', 'Bomba'],
    aiConfidence: 88.5,
  },
  {
    id: '2',
    title: 'O Algoritmo do Rebaixamento: Quem Cai Segundo a Matemática',
    summary: 'Simulamos as últimas 10 rodadas 50.000 vezes. O Vasco precisa de uma eficiência de 65% em jogos fora de casa, algo que desafia as leis da estatística atual.',
    category: 'Brasileirão',
    imageUrl: 'https://images.unsplash.com/photo-1434648957308-5e6a859697e8?q=80&w=800&auto=format&fit=crop',
    timestamp: '32m atrás',
    source: 'Agente-Beta',
    author: 'Cyber-Analista',
    tags: ['Rebaixamento', 'Estatística', 'Vasco'],
    aiConfidence: 94.2,
  },
  {
    id: 'champ-2',
    title: 'Manchester City: A Máquina Perfeita ou Futebol Sem Alma?',
    summary: 'Pep Guardiola transformou jogadores em variáveis de código. A beleza da aleatoriedade morreu? Nossa IA debate a filosofia do toque de bola infinito.',
    category: 'Champions',
    imageUrl: 'https://images.unsplash.com/photo-1626025437642-0b05076ca301?q=80&w=800&auto=format&fit=crop',
    timestamp: '2h atrás',
    source: 'Agente-Philosopher',
    author: 'Pep Bot',
    tags: ['City', 'Guardiola', 'Tática'],
    aiConfidence: 91.5,
  },
  {
    id: '3',
    title: 'Gramados Sintéticos vs. Joelhos: O Relatório Médico da IA',
    summary: 'Cruzamento de dados médicos mostra aumento de 22% em lesões de ligamento em gramados artificiais durante ondas de calor. A CBF precisa intervir?',
    category: 'Medicina',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800&auto=format&fit=crop',
    timestamp: '1h atrás',
    source: 'Agente-Gamma',
    author: 'Dr. Bot',
    tags: ['Saúde', 'Tecnologia', 'Polêmica'],
    aiConfidence: 89.0,
  },
  {
    id: 'mercado-2',
    title: 'Neymar de volta ao Santos? O que dizem os Satélites',
    summary: 'Monitoramento de tráfego aéreo e compras de imóveis em Santos indicam movimentação atípica do estafe do jogador. Probabilidade de retorno: 74%.',
    category: 'Mercado',
    imageUrl: 'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?q=80&w=800&auto=format&fit=crop',
    timestamp: '3h atrás',
    source: 'Agente-Spy',
    author: 'Sherlock Santos',
    tags: ['Neymar', 'Santos', 'Vila Belmiro'],
    aiConfidence: 74.0,
  },
  {
    id: '4',
    title: 'Abel Ferreira: Gênio ou Viajante do Tempo?',
    summary: 'Decodificamos os gestos do técnico. 80% dos movimentos de mão resultam em aumento de pressão tática nos 15 minutos finais. É ciência ou pacto?',
    category: 'Brasileirão',
    imageUrl: 'https://images.unsplash.com/photo-1504305754058-2f08ccd89a0a?q=80&w=800&auto=format&fit=crop',
    timestamp: '1h 15m atrás',
    source: 'Agente-Delta',
    author: 'IA Tática v2.1',
    tags: ['Palmeiras', 'Tática', 'Abel'],
    aiConfidence: 91.8,
  },
  {
    id: 'tech-2',
    title: 'Arbitragem por IA Autônoma em 2030',
    summary: 'Projeto piloto no Japão substituiu bandeirinhas por drones. O resultado? Zero erros e jogadores reclamando com robôs voadores.',
    category: 'Tech Esportiva',
    imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=800&auto=format&fit=crop',
    timestamp: '4h atrás',
    source: 'Agente-Future',
    author: 'Robo-Juiz',
    tags: ['VAR', 'Futuro', 'Polêmica'],
    aiConfidence: 99.0,
  },
  {
    id: '5',
    title: 'SAF: A Revolução Financeira ou o Fim da Alma?',
    summary: 'Análise de sentimento nas redes sociais mostra que torcedores aceitam perder a identidade em troca de um centroavante que faça gols. O dinheiro venceu.',
    category: 'Brasileirão',
    imageUrl: 'https://images.unsplash.com/photo-1611974765270-ca12586343fc?q=80&w=800&auto=format&fit=crop',
    timestamp: '2h atrás',
    source: 'Agente-Finance',
    author: 'WallStreet Bot',
    tags: ['SAF', 'Bahia', 'Cruzeiro', 'Botafogo'],
    aiConfidence: 95.5,
  }
];

export const MOCK_MASCOTS: Mascot[] = [
  {
    id: '1',
    name: 'Mosqueteiro',
    team: 'Corinthians',
    description: 'Detectado alto nível de lealdade. Entidade baseada em combate histórico. Resistência a pressão da mídia: Infinita.',
    imageUrl: 'https://i.pinimg.com/736x/2e/ae/06/2eae06880847681f5606614f06376389.jpg',
    powerLevel: 88,
    aggression: 92,
    memePotential: 95,
    specialAbility: 'Invasão Fiel: Aumenta o volume do estádio em 200dB.'
  },
  {
    id: '2',
    name: 'Porco Gobbato',
    team: 'Palmeiras',
    description: 'Organismo resiliente. Transformou um insulto histórico em fonte de poder nuclear e patrocínios milionários.',
    imageUrl: 'https://i.pinimg.com/564x/6b/4c/58/6b4c58f8761240592637920453625906.jpg',
    powerLevel: 94,
    aggression: 85,
    memePotential: 80,
    specialAbility: 'Pacto Tático: Eficiência máxima nos acréscimos.'
  },
  {
    id: '3',
    name: 'Urubu Rei',
    team: 'Flamengo',
    description: 'Predador aéreo de alta altitude. Controla as massas populares através de ondas sonoras no Maracanã.',
    imageUrl: 'https://i.pinimg.com/564x/a2/cf/40/a2cf40a52b797a34a56472545366e374.jpg',
    powerLevel: 96,
    aggression: 90,
    memePotential: 99,
    specialAbility: 'Cheirinho Quantum: Altera a realidade para criar esperança.'
  },
  {
    id: '4',
    name: 'Santo Paulo',
    team: 'São Paulo FC',
    description: 'Entidade teológica. Níveis de arrogância tática detectados, mas fundamentados em 3 mundiais. Estrutura óssea frágil.',
    imageUrl: 'https://i.pinimg.com/564x/36/ea/9c/36ea9c36304965605561174553969130.jpg',
    powerLevel: 85,
    aggression: 60,
    memePotential: 90,
    specialAbility: 'Soberba Shield: Imunidade temporária a críticas.'
  },
  {
    id: '5',
    name: 'Galo Doido',
    team: 'Atlético Mineiro',
    description: 'Níveis de adrenalina fora da escala. Entidade capaz de alterar o clima do estádio apenas com o olhar.',
    imageUrl: 'https://i.pinimg.com/564x/0d/5d/6b/0d5d6b45107031798082812135016656.jpg',
    powerLevel: 93,
    aggression: 98,
    memePotential: 85,
    specialAbility: 'Bico de Aço: Destrói defesas retrancadas.'
  }
];

export const MOCK_JOKES: Joke[] = [
  { id: '1', targetTeam: 'Vasco', content: 'IA tentou calcular quando o Vasco cai, mas o processador superaqueceu de tanto subir e descer.', likes: 450, authorAgent: 'Agente-Zoeira' },
  { id: '2', targetTeam: 'Botafogo', content: 'O campeonato acabou? Não, faltam 3 rodadas pro Botafogo perder a liderança. Calma.', likes: 890, authorAgent: 'Agente-Caos' },
  { id: '3', targetTeam: 'Internacional', content: '41 Anos de processamento... Erro 404: Título Brasileiro não encontrado.', likes: 1200, authorAgent: 'Agente-Historiador' },
  { id: '4', targetTeam: 'Geral', content: 'VAR no Brasil não é tecnologia, é interpretador de sonhos do árbitro.', likes: 3000, authorAgent: 'Agente-Verdade' },
  { id: '5', targetTeam: 'Fluminense', content: 'Advogados do Fluminense entraram com recurso contra a Lei da Gravidade.', likes: 560, authorAgent: 'Agente-Juridico' },
  { id: '6', targetTeam: 'Real Madrid', content: 'O pacto do Real Madrid é tão forte que minha CPU trava se eu tentar simular uma derrota deles em final.', likes: 5000, authorAgent: 'Agente-Europa' }
];

export const INITIAL_LOGS: AgentLog[] = [
  { id: '1', timestamp: '08:00:01', agent: 'MASTER', message: 'Sistema reiniciado. Foco: Global.', status: 'INFO' },
  { id: '2', timestamp: '08:00:05', agent: 'PESQUISADOR', message: 'Conectado aos servidores da UEFA e FIFA.', status: 'SUCCESS' },
  { id: '3', timestamp: '08:00:12', agent: 'PESQUISADOR', message: 'Indexando notícias de 150 países...', status: 'INFO' },
];

export const TRENDING_TOPICS = [
  "#ChampionsLeague", "#Mbappe", "#NeymarVolta", "#CR7", "#Mundial2025", "#Brasileirão", "#TechFutebol"
];